fos_rest:
  param_fetcher_listener: true
  routing_loader:
    default_format: json
    include_format: false
  view:
    view_response_listener: force
    serialize_null: true
    default_engine: jms.serializer
  format_listener:
    rules:
      - { path: ^/, priorities: [json], fallback_format: json, prefer_extension: false }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  serializer:
    serialize_null: true
