# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  env(MONGODB_URL): ''
  env(MONGODB_DB): ''
  env(CACHE_DSN): ''

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    autowire: false
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  Elasticsearch\Client:
    factory: '@App\Elasticsearch\ClientFactory'

  cache:
    class: '\Redis'
    public: true
    factory: ['Symfony\Component\Cache\Adapter\RedisAdapter','createConnection']
    arguments: ['redis://internal-cache']

  App\Elasticsearch\Indexer:
    arguments:
      $serializer: "@jms_serializer.serializer"
      $elasticSearchClient: '@Elasticsearch\Client'

  App\MessageHandler\Crawler\DataGovRo\DataSetDetailsUpdateHandler:
    calls:
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]
    arguments:
      $sourceRepository: '@App\Repository\Entity\OpenData\SourceRepository'
  App\MessageHandler\Crawler\DataGovRo\DataSetDownloadHandler:
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]
  App\MessageHandler\Crawler\DataGovRo\DataSetProcessorHandler:
    calls:
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]
    arguments:
      $sourceRepository: '@App\Repository\Entity\OpenData\SourceRepository'
  App\MessageHandler\Crawler\DataGovRo\Siruta\ProcessSirutaHandler:
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]

  App\MessageHandler\Crawler\DataGovRo\PostalCodes\ProcessPostalCodesHandler:
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]
  App\MessageHandler\Crawler\DataGovRo\Streets\ProcessStreetsHandler:
    arguments:
      $cache: '@cache'
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]
      - ['setSerializer',['@jms_serializer.serializer']]

  App\MessageHandler\Crawler\DataGovRo\Siruta\LoadZonesHandler:
    arguments:
      $zoneRepository: '@App\Repository\Entity\Administrative\ZoneRepository'
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]

  App\MessageHandler\Crawler\DataGovRo\Siruta\LoadCountiesHandler:
    arguments:
      $zoneRepository: '@App\Repository\Entity\Administrative\ZoneRepository'
      $countyRepository: '@App\Repository\Entity\Administrative\CountyRepository'
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]

  App\MessageHandler\Crawler\DataGovRo\Siruta\LoadAdministrativeUnitsHandler:
    arguments:
      $administrativeUnitRepository: '@App\Repository\Entity\Administrative\AdministrativeUnitRepository'
      $countyRepository: '@App\Repository\Entity\Administrative\CountyRepository'
    calls:
      - ['setProjectDir',['%kernel.project_dir%']]
      - ['setMessageBus',['@message_bus']]
      - ['setGraphEntityManager',['@neo4j.entity_manager.default']]

  App\Repository\Entity\Administrative\AdministrativeUnitRepository:
    calls:
      - ['setCache',['@cache']]

  App\Command\DataGovRo\PruneCommand:
    arguments:
      $cache: '@cache'
